name: CRON

on:
  schedule:
    - cron: '0 16 * * *' # At 16:00 everyday
  workflow_dispatch:

jobs:
  daily-test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '~1.16'

      - name: unit test
        run: |
          deno test -c deno.config.json -j
