name: Build Docker Images

on:
  release:
    types: [created]
  pull_request:
    branches:
      - master
    types:
      - 'closed'
  workflow_dispatch:
    inputs:
      manual:
        description: 'input to trigger manual release'
        required: true
        default: 'yes'

jobs:
  build-docker:
    # this job will only run if the PR has been merged (not if it's just closed) or if it is triggered manually
    if: github.event.pull_request.merged == true || contains(github.event.inputs.manual, 'yes')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image and Push to Registry
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/github-actions-demo:latest
            ghcr.io/${{ github.repository_owner }}/github-actions-demo:${{ github.run_id }}
